### ISSUE TITLE
What is "channel"?

### ISSUE THREAD

**Issue by joshuawallace** [adrn/PrincetonStatsSeminar#2]
In the README file, what is meant by "channel"?  I haven't encountered this word in this context before.

**Comment by adrn** [comment]
I'm not seeing that word in the README, but it is in the `environment.yml` file. A channel is basically a repository of packages to search in. The astropy channel includes a few extra packages that we use frequently in astronomy -- see a list here: https://github.com/astropy/conda-channel-astropy/tree/master/recipe_templates

But, in fact, that line doesn't do anything here because we're not installing any of those packages with conda. I had originally put `astroml` in the package list so for that it would be necessary, now it doesn't actually do anything!

**Comment by joshuawallace** [comment]
Ah yes, that's the file I should have referred to.  Thanks for answering my question.
